name: Notify Project Card Events

on:
  project_card:
    types: [ created ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: lab
        SLACK_FOOTER: ${{ github.event.project_card.url }}
        SLACK_TITLE: Project Card Added
        SLACK_MESSAGE: |
          ${{ github.event.project_card.url }}
          ${{ github.event.project_card.note }}
        MSG_MINIMAL: true
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
